name: Clippy check

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]

# Make sure CI fails on all warnings, including Clippy lints
env:
    RUSTFLAGS: "-Dwarnings"  

jobs:
  release:
    name: Clippy check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: dtolnay/rust-toolchain@stable
      - name: Clippy
        run: |
          cargo clippy --all-targets --all-features