name: Compile test

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-pc-windows-msvc, x86_64-unknown-linux-gnu]
    steps:
      - uses: actions/checkout@master
      - uses: dtolnay/rust-toolchain@stable
      - name: Compile
        run: |
          rustup target add ${{ matrix.target }}
          cargo build --release --target ${{ matrix.target }}
      - name: Publish packaged artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}-release
          path: target/${{ matrix.target }}/release/